### ISSUE TITLE
Crash Reports

### ISSUE THREAD

**Issue by TheHappyMurloc** [janagyjr/tcgs-chillpack-2#1]
[crash-2017-11-25_00.07.12-client.txt](https://github.com/janagyjr/chill-pack-2/files/1503060/crash-2017-11-25_00.07.12-client.txt)
[crash-2017-11-25_00.56.33-client.txt](https://github.com/janagyjr/chill-pack-2/files/1503061/crash-2017-11-25_00.56.33-client.txt)
[crash-2017-11-24_07.42.13-client.txt](https://github.com/janagyjr/chill-pack-2/files/1503062/crash-2017-11-24_07.42.13-client.txt)
[crash-2017-11-24_23.58.49-client.txt](https://github.com/janagyjr/chill-pack-2/files/1503063/crash-2017-11-24_23.58.49-client.txt)

**Comment by janagyjr** [comment]
Taking a look at this now.

The version of the pack you were using has been updated. Try updating the pack to 0.0.2

**Comment by janagyjr** [comment]
Issue resolved by player updating to latest optifine.
